name: xphasepro
description: A new Flutter FFI plugin project.
version: 0.0.1
#homepage:

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.0.2
  path: ^1.8.2
  async: ^2.10.0
  dio: ^5.3.2

dev_dependencies:
  ffigen: ^6.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true